[package]
name = "z-biz-tool-remote"
version = "0.2.0"
description = "跨平台远程控制桌面客户端"
edition = "2021"

[lib]
name = "z_biz_tool_remote_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
xcap = "0.9.8"
enigo = "0.3"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
